/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerClienteContasReceber;
import controller.ControllerContasReceber;
import controller.ControllerFormaPagamento;
import controller.ControllerVendasCliente;
import controller.ControllerVendasContasReceber;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelCliente;
import model.ModelClientesContasReceber;
import model.ModelContasReceber;
import model.ModelFormaPagamento;
import model.ModelVendas;
import model.ModelVendasCliente;
import model.ModelVendasContasReceber;
import util.ModeloTabela;
import util.BLDatas;
import util.BLMascaras;
import util.Formatador;
import util.LetrasMaiusculas;
import java.text.NumberFormat;

/**
 *
 * @author Veronica
 */
public class ViewContasReceber extends javax.swing.JFrame {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();
    ModelVendas modelVendas = new ModelVendas();
    BLDatas bLDatas = new BLDatas();
    ArrayList<ModelVendas> listaModelVendas = new ArrayList<>();
    ArrayList<ModelFormaPagamento> listaModelFormaPagamento = new ArrayList<>();
    ControllerFormaPagamento controllerFormaPagamento = new ControllerFormaPagamento();
    BLMascaras bLMascaras = new BLMascaras();
    ModelFormaPagamento modelFormaPagamento = new ModelFormaPagamento();
    ControllerFormaPagamento controllerFormaPagamento1 = new ControllerFormaPagamento();
    ModelContasReceber modelContasReceber = new ModelContasReceber();
    ArrayList<ModelContasReceber> listaModelContasReceber = new ArrayList<>();
    ControllerContasReceber controllerContasReceber = new ControllerContasReceber();
    ArrayList<ModelVendasCliente> listaModelVendasCliente = new ArrayList<>();
    ControllerVendasCliente controllerVendasCliente = new ControllerVendasCliente();
    ModelVendasCliente modelVendasCliente = new ModelVendasCliente();
    ControllerClienteContasReceber controllerClienteContasReceber = new ControllerClienteContasReceber();
    ArrayList<ModelClientesContasReceber> listaModelClientesContasReceber = new ArrayList<>();
    ArrayList<ModelVendasContasReceber> listaModelVendasContasReceber = new ArrayList<>();
    ModelVendasContasReceber modelVendasContasReceber = new ModelVendasContasReceber();
    ControllerVendasContasReceber controllerVendasContasReceber = new ControllerVendasContasReceber();
    Formatador formatador = new Formatador();
    String salvarAlterar;
    String receberRevogar;

    /**
     * Creates new form ViewCaixa
     */
    public ViewContasReceber() {
        initComponents();
        setLocationRelativeTo(null);
        listaFormaPagamento();
        listarClientes();
        preencherCodigoClientePeloCombobox();
        preencherCodigoFormaPagamentoPeloCombobox();
        jtfCodigoPagamento.setVisible(false);
        habilitaDesabilitaCampos(false);
        habilitaCamposPagamento(false);
        letraMaiuscula();
        carregarContasReceber();
        carregarContasRecebidas();
        calcularPagamento();
        setIcone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PesquisaContasReceber = new javax.swing.ButtonGroup();
        PesquisaContasRecebidas = new javax.swing.ButtonGroup();
        uJPanelImagem7 = new componentes.UJPanelImagem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        jbNovo = new javax.swing.JButton();
        jbReceber = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jbVisualizar1 = new javax.swing.JButton();
        jrbCodigo = new javax.swing.JRadioButton();
        jtfPesquisar = new javax.swing.JTextField();
        jrbDescricao = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtContasReceber = new javax.swing.JTable();
        jrbNomeFornecedor = new javax.swing.JRadioButton();
        jbExcluir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        uJPanelImagem2 = new componentes.UJPanelImagem();
        jbRevogar = new javax.swing.JButton();
        jbVisualizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtContasRecebidas = new javax.swing.JTable();
        jrbCodigo1 = new javax.swing.JRadioButton();
        jrbDescricao1 = new javax.swing.JRadioButton();
        jrbNomeFornecedor1 = new javax.swing.JRadioButton();
        jtfPesquisarRecebidas = new javax.swing.JTextField();
        jbPesquisarRecebidas = new javax.swing.JButton();
        uJPanelImagem3 = new componentes.UJPanelImagem();
        jtfCodigoPagamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfData = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jtfVencimento = new com.toedter.calendar.JDateChooser();
        jtfNumeroConta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfPagamento = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfValor = new javax.swing.JTextField();
        jcbNomeCliente = new componentes.UJComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaObservacao = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jtfDescricao = new javax.swing.JTextField();
        jtfCodigoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbPagamento = new componentes.UJComboBox();
        jLabel6 = new javax.swing.JLabel();
        uJPanelImagem4 = new componentes.UJPanelImagem();
        uJPanelImagem5 = new componentes.UJPanelImagem();
        jButton7 = new javax.swing.JButton();
        jtfCobrar = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jtfTroco = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jtfReceber = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jtfJuros = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jtfValorDivida = new javax.swing.JTextField();
        uJPanelImagem6 = new componentes.UJPanelImagem();
        jButton10 = new javax.swing.JButton();
        jtfCodigoConta = new javax.swing.JTextField();
        jtfDescricaoConta = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfVencimento1 = new javax.swing.JTextField();
        uJPanelImagem8 = new componentes.UJPanelImagem();
        jButton1 = new javax.swing.JButton();
        jtfCodigoFormaPagamento1 = new javax.swing.JTextField();
        jcbFormaPagamento1 = new componentes.UJComboBox();
        jbCancelarConta = new javax.swing.JButton();
        jbSalvarConta = new javax.swing.JButton();

        javax.swing.GroupLayout uJPanelImagem7Layout = new javax.swing.GroupLayout(uJPanelImagem7);
        uJPanelImagem7.setLayout(uJPanelImagem7Layout);
        uJPanelImagem7Layout.setHorizontalGroup(
            uJPanelImagem7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        uJPanelImagem7Layout.setVerticalGroup(
            uJPanelImagem7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Financeiro a Receber");
        setResizable(false);

        uJPanelImagem1.setImagem(new java.io.File("D:\\VendasRenan\\src\\imagens\\flamengo.png"));

        jbNovo.setBackground(new java.awt.Color(255, 255, 255));
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/adicionar.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbReceber.setBackground(new java.awt.Color(255, 255, 255));
        jbReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/receber.png"))); // NOI18N
        jbReceber.setText("Receber Conta");
        jbReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReceberActionPerformed(evt);
            }
        });

        jbPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/procurar.png"))); // NOI18N
        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Descrição:");

        jbVisualizar1.setBackground(new java.awt.Color(255, 255, 255));
        jbVisualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Visualizar.png"))); // NOI18N
        jbVisualizar1.setText("Visualizar Receber");
        jbVisualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizar1ActionPerformed(evt);
            }
        });

        PesquisaContasReceber.add(jrbCodigo);
        jrbCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jrbCodigo.setText("Codigo");

        PesquisaContasReceber.add(jrbDescricao);
        jrbDescricao.setForeground(new java.awt.Color(255, 255, 255));
        jrbDescricao.setText("Descrição");

        jtContasReceber.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtContasReceber);

        PesquisaContasReceber.add(jrbNomeFornecedor);
        jrbNomeFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        jrbNomeFornecedor.setSelected(true);
        jrbNomeFornecedor.setText("Nome Cliente");

        jbExcluir.setBackground(new java.awt.Color(255, 255, 255));
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/excluir.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbAlterar.setBackground(new java.awt.Color(255, 255, 255));
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/alterar.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(42, 42, 42)
                                .addComponent(jrbCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(jrbDescricao)
                                .addGap(18, 18, 18)
                                .addComponent(jrbNomeFornecedor))
                            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                                .addComponent(jtfPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(jbPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(jbVisualizar1)))))
                .addContainerGap())
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbExcluir)
                .addGap(51, 51, 51)
                .addComponent(jbAlterar)
                .addGap(64, 64, 64)
                .addComponent(jbNovo)
                .addGap(223, 223, 223)
                .addComponent(jbReceber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrbCodigo)
                        .addComponent(jrbNomeFornecedor)
                        .addComponent(jrbDescricao))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar)
                    .addComponent(jbVisualizar1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbExcluir)
                    .addComponent(jbAlterar)
                    .addComponent(jbNovo)
                    .addComponent(jbReceber))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contas a Receber", uJPanelImagem1);

        uJPanelImagem2.setImagem(new java.io.File("D:\\VendasRenan\\src\\imagens\\flamengo.png"));

        jbRevogar.setBackground(new java.awt.Color(255, 255, 255));
        jbRevogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/excluir.png"))); // NOI18N
        jbRevogar.setText("Revogar Pagamento");
        jbRevogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRevogarActionPerformed(evt);
            }
        });

        jbVisualizar.setBackground(new java.awt.Color(255, 255, 255));
        jbVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/Visualizar.png"))); // NOI18N
        jbVisualizar.setText("Visualizar Venda");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Descrição:");

        jtContasRecebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtContasRecebidas);

        PesquisaContasRecebidas.add(jrbCodigo1);
        jrbCodigo1.setForeground(new java.awt.Color(255, 255, 255));
        jrbCodigo1.setText("Codigo");

        PesquisaContasRecebidas.add(jrbDescricao1);
        jrbDescricao1.setForeground(new java.awt.Color(255, 255, 255));
        jrbDescricao1.setText("Descrição");

        PesquisaContasRecebidas.add(jrbNomeFornecedor1);
        jrbNomeFornecedor1.setForeground(new java.awt.Color(255, 255, 255));
        jrbNomeFornecedor1.setSelected(true);
        jrbNomeFornecedor1.setText("Nome Cliente");

        jbPesquisarRecebidas.setBackground(new java.awt.Color(255, 255, 255));
        jbPesquisarRecebidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/procurar.png"))); // NOI18N
        jbPesquisarRecebidas.setText("Pesquisar");
        jbPesquisarRecebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarRecebidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uJPanelImagem2Layout = new javax.swing.GroupLayout(uJPanelImagem2);
        uJPanelImagem2.setLayout(uJPanelImagem2Layout);
        uJPanelImagem2Layout.setHorizontalGroup(
            uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbRevogar))
                    .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(40, 40, 40)
                                .addComponent(jrbCodigo1)
                                .addGap(18, 18, 18)
                                .addComponent(jrbDescricao1)
                                .addGap(18, 18, 18)
                                .addComponent(jrbNomeFornecedor1))
                            .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                                .addComponent(jtfPesquisarRecebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPesquisarRecebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbVisualizar)))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        uJPanelImagem2Layout.setVerticalGroup(
            uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrbCodigo1)
                        .addComponent(jrbNomeFornecedor1)
                        .addComponent(jrbDescricao1))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPesquisarRecebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisarRecebidas)
                    .addComponent(jbVisualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbRevogar)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Contas Recebidas", uJPanelImagem2);

        uJPanelImagem3.setImagem(new java.io.File("D:\\VendasRenan\\src\\imagens\\flamengo.png"));

        jtfCodigoPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfCodigoPagamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoPagamentoFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pagamento:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valor:");

        jtfNumeroConta.setEditable(false);
        jtfNumeroConta.setBackground(new java.awt.Color(204, 255, 204));
        jtfNumeroConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfNumeroConta.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pagamento:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número da conta:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Observação:");

        jcbNomeCliente.setAutocompletar(true);
        jcbNomeCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbNomeCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbNomeClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jtaObservacao.setColumns(20);
        jtaObservacao.setRows(5);
        jScrollPane3.setViewportView(jtaObservacao);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome do Cliente:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código do Cliente:");

        jbCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descrição da conta:");

        jbSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/18x18/salvar2.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        jbSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbSalvarKeyPressed(evt);
            }
        });

        jtfDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDescricaoFocusLost(evt);
            }
        });
        jtfDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDescricaoActionPerformed(evt);
            }
        });

        jtfCodigoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfCodigoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoClienteFocusLost(evt);
            }
        });
        jtfCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoClienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data:");

        jcbPagamento.setAutocompletar(true);
        jcbPagamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbPagamento.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbPagamentoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vencimento:");

        javax.swing.GroupLayout uJPanelImagem3Layout = new javax.swing.GroupLayout(uJPanelImagem3);
        uJPanelImagem3.setLayout(uJPanelImagem3Layout);
        uJPanelImagem3Layout.setHorizontalGroup(
            uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                        .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                        .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDescricao)
                            .addComponent(jScrollPane3)
                            .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfCodigoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                                .addComponent(jbCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbSalvar))
                            .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(21, 21, 21)
                                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(160, 160, 160))
                                    .addComponent(jtfValor)))
                            .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(jtfCodigoCliente))
                                .addGap(18, 18, 18)
                                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jcbNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jtfNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        uJPanelImagem3Layout.setVerticalGroup(
            uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                        .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcbNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(jtfNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem3Layout.createSequentialGroup()
                        .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCodigoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(uJPanelImagem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbSalvar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastrar", uJPanelImagem3);

        uJPanelImagem4.setImagem(new java.io.File("D:\\VendasRenan\\src\\imagens\\flamengo.png"));

        jButton7.setText("Cobrar em R$");
        jButton7.setFocusable(false);

        jtfCobrar.setEnabled(false);

        jButton6.setText("Troco");
        jButton6.setFocusable(false);

        jtfTroco.setEnabled(false);

        jButton5.setText("Valor Recebido");
        jButton5.setFocusable(false);

        jtfReceber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfReceberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfReceberFocusLost(evt);
            }
        });
        jtfReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfReceberActionPerformed(evt);
            }
        });

        jButton4.setText("Juros......");
        jButton4.setFocusable(false);

        jtfJuros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfJurosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfJurosFocusLost(evt);
            }
        });
        jtfJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfJurosActionPerformed(evt);
            }
        });

        jButton2.setText("Valor da Dívida");
        jButton2.setFocusable(false);

        jtfValorDivida.setEditable(false);
        jtfValorDivida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtfValorDivida.setFocusable(false);

        javax.swing.GroupLayout uJPanelImagem5Layout = new javax.swing.GroupLayout(uJPanelImagem5);
        uJPanelImagem5.setLayout(uJPanelImagem5Layout);
        uJPanelImagem5Layout.setHorizontalGroup(
            uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uJPanelImagem5Layout.createSequentialGroup()
                        .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(uJPanelImagem5Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 22, Short.MAX_VALUE))
                            .addGroup(uJPanelImagem5Layout.createSequentialGroup()
                                .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22)))
                        .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(uJPanelImagem5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfTroco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCobrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(uJPanelImagem5Layout.createSequentialGroup()
                                .addComponent(jtfValorDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(uJPanelImagem5Layout.createSequentialGroup()
                        .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfJuros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfReceber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        uJPanelImagem5Layout.setVerticalGroup(
            uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValorDivida))
                .addGap(18, 18, 18)
                .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfJuros))
                .addGap(18, 18, 18)
                .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfReceber))
                .addGap(11, 11, 11)
                .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfTroco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(uJPanelImagem5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton10.setText("Dados Conta");
        jButton10.setFocusable(false);

        jtfCodigoConta.setEnabled(false);

        jtfDescricaoConta.setEnabled(false);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Vencimento:");

        jtfVencimento1.setEnabled(false);

        javax.swing.GroupLayout uJPanelImagem6Layout = new javax.swing.GroupLayout(uJPanelImagem6);
        uJPanelImagem6.setLayout(uJPanelImagem6Layout);
        uJPanelImagem6Layout.setHorizontalGroup(
            uJPanelImagem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uJPanelImagem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addGroup(uJPanelImagem6Layout.createSequentialGroup()
                        .addGroup(uJPanelImagem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodigoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(uJPanelImagem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfVencimento1)
                            .addComponent(jtfDescricaoConta))))
                .addContainerGap())
        );
        uJPanelImagem6Layout.setVerticalGroup(
            uJPanelImagem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDescricaoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(uJPanelImagem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfVencimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Forma Pagamento");
        jButton1.setFocusable(false);

        jtfCodigoFormaPagamento1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFormaPagamento1FocusLost(evt);
            }
        });

        jcbFormaPagamento1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jcbFormaPagamento1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jcbFormaPagamento1PopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout uJPanelImagem8Layout = new javax.swing.GroupLayout(uJPanelImagem8);
        uJPanelImagem8.setLayout(uJPanelImagem8Layout);
        uJPanelImagem8Layout.setHorizontalGroup(
            uJPanelImagem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uJPanelImagem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(uJPanelImagem8Layout.createSequentialGroup()
                        .addComponent(jtfCodigoFormaPagamento1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbFormaPagamento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        uJPanelImagem8Layout.setVerticalGroup(
            uJPanelImagem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uJPanelImagem8Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addGroup(uJPanelImagem8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigoFormaPagamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbFormaPagamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jbCancelarConta.setBackground(new java.awt.Color(255, 255, 255));
        jbCancelarConta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbCancelarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/cancelar.png"))); // NOI18N
        jbCancelarConta.setText("Cancelar");
        jbCancelarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarContaActionPerformed(evt);
            }
        });

        jbSalvarConta.setBackground(new java.awt.Color(255, 255, 255));
        jbSalvarConta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSalvarConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/32x32/salvar2.png"))); // NOI18N
        jbSalvarConta.setText("Salvar");
        jbSalvarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uJPanelImagem4Layout = new javax.swing.GroupLayout(uJPanelImagem4);
        uJPanelImagem4.setLayout(uJPanelImagem4Layout);
        uJPanelImagem4Layout.setHorizontalGroup(
            uJPanelImagem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(uJPanelImagem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(uJPanelImagem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uJPanelImagem6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uJPanelImagem8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(uJPanelImagem4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jbCancelarConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalvarConta)
                .addGap(49, 49, 49))
        );
        uJPanelImagem4Layout.setVerticalGroup(
            uJPanelImagem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem4Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(uJPanelImagem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uJPanelImagem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(uJPanelImagem4Layout.createSequentialGroup()
                        .addComponent(uJPanelImagem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(uJPanelImagem8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(uJPanelImagem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelarConta)
                    .addComponent(jbSalvarConta))
                .addGap(89, 89, 89))
        );

        jTabbedPane1.addTab("Receber Conta", uJPanelImagem4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        // TODO add your handling code here:
        ModeloTabela modelo = (ModeloTabela) this.jtContasReceber.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jtContasReceber.setRowSorter(classificador);
        String texto = this.jtfPesquisar.getText();
        if (jrbCodigo.isSelected() == true) {
            classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
        } else if (jrbDescricao.isSelected() == true) {
            classificador.setRowFilter(RowFilter.regexFilter(texto, 2));
        } else if (jrbNomeFornecedor.isSelected() == true) {
            classificador.setRowFilter(RowFilter.regexFilter(texto, 3));
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jcbNomeClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbNomeClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (jcbNomeCliente.isPopupVisible()) {
            preencherCodigoClientePeloCombobox();
        }
    }//GEN-LAST:event_jcbNomeClientePopupMenuWillBecomeInvisible

    private void jbPesquisarRecebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarRecebidasActionPerformed
        // TODO add your handling code here:
        ModeloTabela modelo = (ModeloTabela) this.jtContasRecebidas.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jtContasRecebidas.setRowSorter(classificador);
        String texto = this.jtfPesquisarRecebidas.getText();
        if (jrbCodigo1.isSelected() == true) {
            classificador.setRowFilter(RowFilter.regexFilter(texto, 0));
        } else if (jrbDescricao1.isSelected() == true) {
            classificador.setRowFilter(RowFilter.regexFilter(texto, 2));
        } else if (jrbNomeFornecedor1.isSelected() == true) {
            classificador.setRowFilter(RowFilter.regexFilter(texto, 3));
        }
    }//GEN-LAST:event_jbPesquisarRecebidasActionPerformed

    private void jtfCodigoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoClienteFocusLost
        // TODO add your handling code here:
        try {
            modelCliente = controllerCliente.getClienteController(Integer.parseInt(jtfCodigoCliente.getText()));
            jcbNomeCliente.setSelectedItem(modelCliente.getCliNome());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jtfCodigoClienteFocusLost

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        this.limpaFormulario();
        this.habilitaDesabilitaCampos(false);
        this.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        if (salvarAlterar.equals("salvar")) {
            try {
                salvarConta();
            } catch (Exception ex) {
                Logger.getLogger(ViewContasReceber.class.getName()).log(Level.SEVERE, null, ex);
            }
            jTabbedPane1.setSelectedIndex(0);
        }
        if (salvarAlterar.equals("alterar")) {
            alterarConta();
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        // TODO add your handling code here:
        this.habilitaDesabilitaCampos(true);
        salvarAlterar = "salvar";
        jTabbedPane1.setSelectedIndex(2);
        jtfCodigoCliente.requestFocus();
        jtfCodigoCliente.selectAll();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbRevogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRevogarActionPerformed
        // TODO add your handling code here:
        try {
            int linha = jtContasRecebidas.getSelectedRow();

            modelContasReceber.setIdContasReceber((int) jtContasRecebidas.getValueAt(linha, 0));

//            modelContasReceber.setPagamentoContasReceber(null);
            modelContasReceber.setSituaçãoContasReceber(0);

            if (controllerContasReceber.atualizarContasRecebidasController(modelContasReceber)) {
                JOptionPane.showMessageDialog(this, "Conta revogada com sucesso", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                this.carregarContasReceber();
                this.carregarContasRecebidas();
                jTabbedPane1.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao revogar conta", "ERRO", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Selecione uma conta na tabela", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbRevogarActionPerformed

    private void jbReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReceberActionPerformed
        // TODO add your handling code here:
        try {
            receberRevogar = "receber";

            habilitaCamposPagamento(true);
            int linha = jtContasReceber.getSelectedRow();
            int codigoContaReceber = (int) jtContasReceber.getValueAt(linha, 0);
            listaModelClientesContasReceber = controllerClienteContasReceber.getListaClienteContasReceberController(codigoContaReceber);

            jtfCodigoConta.setText(jtContasReceber.getValueAt(linha, 0).toString());
            jtfDescricaoConta.setText(jtContasReceber.getValueAt(linha, 2).toString());
            jtfVencimento1.setText(jtContasReceber.getValueAt(linha, 5).toString());
            jtfValorDivida.setText(jtContasReceber.getValueAt(linha, 7).toString());

            jTabbedPane1.setSelectedIndex(3);
            calcularPagamento();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione uma conta na tabela", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbReceberActionPerformed

    private void habilitaCamposPagamento(boolean condicao) {
        jtfCodigoFormaPagamento1.setEnabled(condicao);
        jcbFormaPagamento1.setEnabled(condicao);
        jtfJuros.setEnabled(condicao);
        jbCancelarConta.setEnabled(condicao);
        jtfReceber.setEnabled(condicao);
    }

    private void limpaCamposPagamento() {
        jtfValorDivida.setText("");
        jtfDescricaoConta.setText("");
        jtfVencimento1.setText("");
        jcbFormaPagamento1.setSelectedItem("");
        jtfCodigoConta.setText("");
        jtfJuros.setText("");
        jtfTroco.setText("");
        jtfReceber.setText("");
    }

    /**
     * calcula o valor total a pagar e troco
     */
    private void calcularPagamento() {

        double juros, receber, troco, total, valorDivida;
        try {
            valorDivida = Double.parseDouble(jtfValorDivida.getText());
        } catch (Exception e) {
            valorDivida = 0;
        }
        try {
            juros = Double.parseDouble(jtfJuros.getText());
        } catch (Exception e) {
            juros = 0;
            jtfJuros.setText("0");
        }
        try {
            receber = Double.parseDouble(jtfReceber.getText());
        } catch (Exception e) {
            receber = 0;
        }

        //calcular valor total
        total = valorDivida + juros;
        jtfCobrar.setText(bLMascaras.arredondamentoComPontoDuasCasasString(total));
        //calcular troco
        troco = receber - total;
        jtfTroco.setText(bLMascaras.arredondamentoComPontoDuasCasasString(troco));
    }

    private void jtfCodigoPagamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoPagamentoFocusLost
        // TODO add your handling code here:
        modelFormaPagamento = controllerFormaPagamento.getFormaPagamentoController(Integer.parseInt(jtfCodigoPagamento.getText()));
        jcbPagamento.setSelectedItem(modelFormaPagamento.getDescricaoFormaPagamento());
    }//GEN-LAST:event_jtfCodigoPagamentoFocusLost

    private void jcbPagamentoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbPagamentoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (jcbPagamento.isPopupVisible()) {
            preencherCodigoFormaPagamentoPeloCombobox();
        }
    }//GEN-LAST:event_jcbPagamentoPopupMenuWillBecomeInvisible

    private void jtfCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoClienteActionPerformed
        // TODO add your handling code here:
        jtfDescricao.requestFocus();
    }//GEN-LAST:event_jtfCodigoClienteActionPerformed

    private void jtfDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDescricaoActionPerformed
        // TODO add your handling code here:
        jtfData.requestFocus();
    }//GEN-LAST:event_jtfDescricaoActionPerformed

    private void jbSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSalvarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSalvarKeyPressed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        int linha = jtContasReceber.getSelectedRow();

        try {

            int codigoContaReceber = (int) jtContasReceber.getValueAt(linha, 0);

            switch (JOptionPane.showConfirmDialog(null, "Deseja excluir a conta selecionado", "EXCLUSÃO DE CONTA", JOptionPane.YES_NO_OPTION)) {
                case 0:
                    controllerContasReceber.excluirContasReceberController(codigoContaReceber);
                    this.carregarContasReceber();
                    this.habilitaDesabilitaCampos(false);
                    break;
                case 1:
//                    JOptionPane.showMessageDialog(this, "Cancelado pelo usuário!", "ERRO", JOptionPane.ERROR_MESSAGE);
                    break;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nenhum registro selecionado!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        habilitaDesabilitaCampos(true);
        salvarAlterar = "alterar";

        int linha = jtContasReceber.getSelectedRow();
        int codigoContaReceber = (int) jtContasReceber.getValueAt(linha, 0);
        listaModelClientesContasReceber = controllerClienteContasReceber.getListaClienteContasReceberController(codigoContaReceber);
        int cont = listaModelClientesContasReceber.size();

        for (int i = 0; i < cont; i++) {
            jtfNumeroConta.setText(String.valueOf(listaModelClientesContasReceber.get(i).getModelContasReceber().getIdContasReceber()));
            jtfCodigoCliente.setText(String.valueOf(listaModelClientesContasReceber.get(i).getModelCliente().getIdCliente()));
            jcbNomeCliente.setSelectedItem(String.valueOf(listaModelClientesContasReceber.get(i).getModelCliente().getCliNome()));
            jtfDescricao.setText(String.valueOf(listaModelClientesContasReceber.get(i).getModelContasReceber().getDescricaoContasReceber()));
            jtfData.setDate(listaModelClientesContasReceber.get(i).getModelContasReceber().getDataContasReceber());
            jtfVencimento.setDate(listaModelClientesContasReceber.get(i).getModelContasReceber().getVencimentoContasReceber());
            jtfValor.setText(String.valueOf(listaModelClientesContasReceber.get(i).getModelContasReceber().getValorContasReceber()));
            jtaObservacao.setText(String.valueOf(listaModelClientesContasReceber.get(i).getModelContasReceber().getObservacaoContasReceber()));
        };
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbVisualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVisualizar1ActionPerformed

    private void jcbFormaPagamento1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbFormaPagamento1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFormaPagamento1PopupMenuWillBecomeVisible

    private void jcbFormaPagamento1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jcbFormaPagamento1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (jcbFormaPagamento1.isPopupVisible()) {
            preencherCodigoFormaPagamentoPeloCombobox1();
        }
    }//GEN-LAST:event_jcbFormaPagamento1PopupMenuWillBecomeInvisible

    private void jtfCodigoFormaPagamento1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFormaPagamento1FocusLost
        // TODO add your handling code here:
        modelFormaPagamento = controllerFormaPagamento.getFormaPagamentoController(Integer.parseInt(jtfCodigoFormaPagamento1.getText()));
        jcbFormaPagamento1.setSelectedItem(modelFormaPagamento.getDescricaoFormaPagamento());
    }//GEN-LAST:event_jtfCodigoFormaPagamento1FocusLost

    private void jbCancelarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarContaActionPerformed
        // TODO add your handling code here:
        habilitaCamposPagamento(false);
        limpaCamposPagamento();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jbCancelarContaActionPerformed

    private void jbSalvarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarContaActionPerformed
        // TODO add your handling code here:
        try {
            modelContasReceber.setIdContasReceber(Integer.parseInt(this.jtfCodigoConta.getText()));
            modelContasReceber.setPagamentoContasReceber(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
            modelContasReceber.setFkPagamento(Integer.parseInt(this.jtfCodigoFormaPagamento1.getText()));
            modelContasReceber.setValorContasReceber(formatador.converterVirgulaParaPontoReturn(this.jtfCobrar.getText()));
            modelContasReceber.setSituaçãoContasReceber(1);
        } catch (Exception e) {
        }

        if (controllerContasReceber.atualizarContasReceberController2(modelContasReceber)) {
            JOptionPane.showMessageDialog(this, "Conta recebida com sucesso", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.limpaCamposPagamento();
            this.habilitaCamposPagamento(false);
            this.carregarContasReceber();
            this.carregarContasRecebidas();
            jTabbedPane1.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao receber conta", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarContaActionPerformed

    private void jtfJurosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfJurosFocusLost
        // TODO add your handling code here:
        calcularPagamento();
    }//GEN-LAST:event_jtfJurosFocusLost

    private void jtfJurosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfJurosFocusGained
        // TODO add your handling code here:
        jtfJuros.selectAll();
    }//GEN-LAST:event_jtfJurosFocusGained

    private void jtfJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfJurosActionPerformed
        // TODO add your handling code here:
        jtfReceber.requestFocus();
    }//GEN-LAST:event_jtfJurosActionPerformed

    private void jtfReceberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfReceberFocusLost
        // TODO add your handling code here:
        calcularPagamento();
    }//GEN-LAST:event_jtfReceberFocusLost

    private void jtfReceberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfReceberFocusGained
        // TODO add your handling code here:
        jtfReceber.selectAll();
    }//GEN-LAST:event_jtfReceberFocusGained

    private void jtfReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfReceberActionPerformed
        // TODO add your handling code here:
        jbSalvarConta.requestFocus();
    }//GEN-LAST:event_jtfReceberActionPerformed

    private void jtfDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDescricaoFocusLost
        try {
            // TODO add your handling code here:
            jtfData.setDate(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
            Logger.getLogger(ViewContasReceber.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtfDescricaoFocusLost

    private void salvarConta() throws Exception {
        try {
            modelContasReceber.setIdContasReceber(Integer.parseInt(this.jtfNumeroConta.getText()));
        } catch (NumberFormatException e) {
        }
        modelContasReceber.setFkCliente(Integer.parseInt(this.jtfCodigoCliente.getText()));
        modelContasReceber.setFkPagamento(Integer.parseInt(this.jtfCodigoPagamento.getText()));
        modelContasReceber.setDescricaoContasReceber(this.jtfDescricao.getText());
        try {
            modelContasReceber.setDataContasReceber(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
            modelContasReceber.setVencimentoContasReceber(bLDatas.converterDataParaDateUS(this.jtfVencimento.getDate()));
            modelContasReceber.setPagamentoContasReceber(bLDatas.converterDataParaDateUS(this.jtfPagamento.getDate()));
        } catch (Exception e) {
        }
        modelContasReceber.setValorContasReceber(formatador.converterVirgulaParaPontoReturn(this.jtfValor.getText()));
        modelContasReceber.setObservacaoContasReceber(this.jtaObservacao.getText());

        if (controllerContasReceber.salvarContasReceberController(modelContasReceber)<0) {
            JOptionPane.showMessageDialog(this, "Conta salva com sucesso", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.limpaFormulario();
            this.habilitaDesabilitaCampos(false);
            this.carregarContasReceber();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao salvar conta", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void alterarConta() {
        try {
            modelContasReceber.setIdContasReceber(Integer.parseInt(this.jtfNumeroConta.getText()));
        } catch (NumberFormatException e) {
        }
        modelContasReceber.setFkCliente(Integer.parseInt(this.jtfCodigoCliente.getText()));
        modelContasReceber.setFkPagamento(Integer.parseInt(this.jtfCodigoPagamento.getText()));
        modelContasReceber.setDescricaoContasReceber(this.jtfDescricao.getText());
        try {
            modelContasReceber.setDataContasReceber(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
            modelContasReceber.setVencimentoContasReceber(bLDatas.converterDataParaDateUS(this.jtfVencimento.getDate()));
            modelContasReceber.setPagamentoContasReceber(bLDatas.converterDataParaDateUS(this.jtfPagamento.getDate()));
        } catch (Exception e) {
        }
        modelContasReceber.setValorContasReceber(formatador.converterVirgulaParaPontoReturn(this.jtfValor.getText()));
        modelContasReceber.setObservacaoContasReceber(this.jtaObservacao.getText());

        if (controllerContasReceber.atualizarContasReceberController(modelContasReceber)) {
            JOptionPane.showMessageDialog(this, "Conta alterada com sucesso", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            this.limpaFormulario();
            this.habilitaDesabilitaCampos(false);
            this.carregarContasReceber();
            jTabbedPane1.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar conta", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Preenche o combobox com com todas formas de pagamento
     */
    private void listaFormaPagamento() {
        listaModelFormaPagamento = controllerFormaPagamento.getListaFormaPagamentoController();
        jcbPagamento.removeAllItems();
        jcbFormaPagamento1.removeAllItems();
        for (int i = 0; i < listaModelFormaPagamento.size(); i++) {
            jcbPagamento.addItem(listaModelFormaPagamento.get(i).getDescricaoFormaPagamento());
            jcbFormaPagamento1.addItem(listaModelFormaPagamento.get(i).getDescricaoFormaPagamento());
        }
    }

    private void letraMaiuscula() {
        jtfDescricao.setDocument(new LetrasMaiusculas());
        jtfPesquisar.setDocument(new LetrasMaiusculas());
        jtfPesquisarRecebidas.setDocument(new LetrasMaiusculas());
    }

    /**
     * preenche o combobox com todos os clientes
     */
    private void listarClientes() {
        listaModelClientes = controllerCliente.getListaClienteController();
        jcbNomeCliente.removeAllItems();
        for (int i = 0; i < listaModelClientes.size(); i++) {
            jcbNomeCliente.addItem(listaModelClientes.get(i).getCliNome());
        }
    }

    private void preencherCodigoClientePeloCombobox() {
        modelCliente = controllerCliente.getClienteController(jcbNomeCliente.getSelectedItem().toString());
        jtfCodigoCliente.setText(String.valueOf(modelCliente.getIdCliente()));
    }

    private void preencherCodigoFormaPagamentoPeloCombobox() {
        modelFormaPagamento = controllerFormaPagamento.getFormaPagamentoController(jcbPagamento.getSelectedItem().toString());
        jtfCodigoPagamento.setText(String.valueOf(modelFormaPagamento.getIdFormaPagamento()));
        jtfCodigoFormaPagamento1.setText(String.valueOf(modelFormaPagamento.getIdFormaPagamento()));
    }

    private void preencherCodigoFormaPagamentoPeloCombobox1() {
        modelFormaPagamento = controllerFormaPagamento.getFormaPagamentoController(jcbFormaPagamento1.getSelectedItem().toString());
        jtfCodigoFormaPagamento1.setText(String.valueOf(modelFormaPagamento.getIdFormaPagamento()));
    }

    private void carregarVendas() {
        listaModelVendasCliente = controllerVendasCliente.getListaVendasClienteController();
        DefaultTableModel modelo = (DefaultTableModel) jtContasReceber.getModel();
        modelo.setNumRows(0);
        int cont = listaModelVendasCliente.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelVendasCliente.get(i).getModelVendas().getIdVenda(),
                listaModelVendasCliente.get(i).getModelCliente().getCliNome(),
                listaModelVendasCliente.get(i).getModelVendas().getVenDataVenda()
            });
        }
    }

    private void limpaFormulario() {
        jtfCodigoCliente.setText("");
        jcbNomeCliente.setSelectedItem("");
        jtfNumeroConta.setText("");
        jtfDescricao.setText("");
        jtfData.setDateFormatString("");
        jtfPagamento.setDateFormatString("");
        jtfVencimento.setDateFormatString("");
        jcbPagamento.setSelectedItem("");
        jtaObservacao.setText("");
        jtfValor.setText("");
        jtfCodigoPagamento.setText("");
    }

    public void carregarContasReceber() {
        ArrayList dados = new ArrayList();

        String[] colunas = new String[]{"Código", "Venda", "Descrição", "Nome do Cliente", "Data", "Vencimento", "Pagamento", "Valor"};

        listaModelClientesContasReceber = controllerClienteContasReceber.getListaClienteContasReceberController2();
        try {
            for (int i = 0; i < listaModelClientesContasReceber.size(); i++) {
                dados.add(new Object[]{
                    listaModelClientesContasReceber.get(i).getModelContasReceber().getIdContasReceber(),
                    listaModelClientesContasReceber.get(i).getModelContasReceber().getFkVenda(),
                    listaModelClientesContasReceber.get(i).getModelContasReceber().getDescricaoContasReceber(),
                    listaModelClientesContasReceber.get(i).getModelCliente().getCliNome(),
                    bLDatas.formatarData(listaModelClientesContasReceber.get(i).getModelContasReceber().getDataContasReceber()),
                    bLDatas.formatarData(listaModelClientesContasReceber.get(i).getModelContasReceber().getVencimentoContasReceber()),
                    bLDatas.formatarData(listaModelClientesContasReceber.get(i).getModelContasReceber().getPagamentoContasReceber()),
                    listaModelClientesContasReceber.get(i).getModelContasReceber().getValorContasReceber()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jtContasReceber.setModel(modelo);
        jtContasReceber.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtContasReceber.getColumnModel().getColumn(0).setResizable(false);
        jtContasReceber.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtContasReceber.getColumnModel().getColumn(1).setResizable(false);
        jtContasReceber.getColumnModel().getColumn(2).setPreferredWidth(180);
        jtContasReceber.getColumnModel().getColumn(2).setResizable(false);
        jtContasReceber.getColumnModel().getColumn(3).setPreferredWidth(300);
        jtContasReceber.getColumnModel().getColumn(3).setResizable(false);
        jtContasReceber.getColumnModel().getColumn(4).setPreferredWidth(100);
        jtContasReceber.getColumnModel().getColumn(4).setResizable(false);
        jtContasReceber.getColumnModel().getColumn(5).setPreferredWidth(100);
        jtContasReceber.getColumnModel().getColumn(5).setResizable(false);
        jtContasReceber.getColumnModel().getColumn(6).setPreferredWidth(100);
        jtContasReceber.getColumnModel().getColumn(6).setResizable(false);
        jtContasReceber.getColumnModel().getColumn(7).setPreferredWidth(100);
        jtContasReceber.getColumnModel().getColumn(7).setResizable(false);
        jtContasReceber.getTableHeader().setReorderingAllowed(false);
        jtContasReceber.setAutoResizeMode(jtContasReceber.AUTO_RESIZE_OFF);
        jtContasReceber.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void carregarContasRecebidas() {
        ArrayList dados = new ArrayList();

        String[] colunas = new String[]{"Código", "Venda", "Descrição", "Nome do Cliente", "Data", "Vencimento", "Pagamento", "Valor"};

        listaModelClientesContasReceber = controllerClienteContasReceber.getListaClienteContasRecebidasController2();
        try {
            for (int i = 0; i < listaModelClientesContasReceber.size(); i++) {
                dados.add(new Object[]{
                    listaModelClientesContasReceber.get(i).getModelContasReceber().getIdContasReceber(),
                    listaModelClientesContasReceber.get(i).getModelContasReceber().getFkVenda(),
                    listaModelClientesContasReceber.get(i).getModelContasReceber().getDescricaoContasReceber(),
                    listaModelClientesContasReceber.get(i).getModelCliente().getCliNome(),
                    bLDatas.formatarData(listaModelClientesContasReceber.get(i).getModelContasReceber().getDataContasReceber()),
                    bLDatas.formatarData(listaModelClientesContasReceber.get(i).getModelContasReceber().getVencimentoContasReceber()),
                    bLDatas.formatarData(listaModelClientesContasReceber.get(i).getModelContasReceber().getPagamentoContasReceber()),
                    NumberFormat.getCurrencyInstance().format(listaModelClientesContasReceber.get(i).getModelContasReceber().getValorContasReceber())
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher o ArrayList!", "ERRO", JOptionPane.ERROR_MESSAGE);
        }

        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jtContasRecebidas.setModel(modelo);
        jtContasRecebidas.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtContasRecebidas.getColumnModel().getColumn(0).setResizable(false);
        jtContasRecebidas.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtContasRecebidas.getColumnModel().getColumn(1).setResizable(false);
        jtContasRecebidas.getColumnModel().getColumn(2).setPreferredWidth(180);
        jtContasRecebidas.getColumnModel().getColumn(2).setResizable(false);
        jtContasRecebidas.getColumnModel().getColumn(3).setPreferredWidth(300);
        jtContasRecebidas.getColumnModel().getColumn(3).setResizable(false);
        jtContasRecebidas.getColumnModel().getColumn(4).setPreferredWidth(100);
        jtContasRecebidas.getColumnModel().getColumn(4).setResizable(false);
        jtContasRecebidas.getColumnModel().getColumn(5).setPreferredWidth(100);
        jtContasRecebidas.getColumnModel().getColumn(5).setResizable(false);
        jtContasRecebidas.getColumnModel().getColumn(6).setPreferredWidth(100);
        jtContasRecebidas.getColumnModel().getColumn(6).setResizable(false);
        jtContasRecebidas.getColumnModel().getColumn(7).setPreferredWidth(100);
        jtContasRecebidas.getColumnModel().getColumn(7).setResizable(false);
        jtContasRecebidas.getTableHeader().setReorderingAllowed(false);
        jtContasRecebidas.setAutoResizeMode(jtContasReceber.AUTO_RESIZE_OFF);
        jtContasRecebidas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void habilitaDesabilitaCampos(boolean condicao) {
        jtfCodigoCliente.setEnabled(condicao);
        jcbNomeCliente.setEnabled(condicao);
        jtfNumeroConta.setEnabled(condicao);
        jtfDescricao.setEnabled(condicao);
        jtfData.setEnabled(condicao);
        jtfVencimento.setEnabled(condicao);
        jtfPagamento.setEnabled(condicao);
        jtfValor.setEnabled(condicao);
        jcbPagamento.setEnabled(condicao);
        jtaObservacao.setEnabled(condicao);
        jbSalvar.setEnabled(condicao);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewContasReceber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewContasReceber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup PesquisaContasReceber;
    private javax.swing.ButtonGroup PesquisaContasRecebidas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCancelarConta;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbPesquisarRecebidas;
    private javax.swing.JButton jbReceber;
    private javax.swing.JButton jbRevogar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JButton jbSalvarConta;
    private javax.swing.JButton jbVisualizar;
    private javax.swing.JButton jbVisualizar1;
    private componentes.UJComboBox jcbFormaPagamento1;
    private componentes.UJComboBox jcbNomeCliente;
    private componentes.UJComboBox jcbPagamento;
    private javax.swing.JRadioButton jrbCodigo;
    private javax.swing.JRadioButton jrbCodigo1;
    private javax.swing.JRadioButton jrbDescricao;
    private javax.swing.JRadioButton jrbDescricao1;
    private javax.swing.JRadioButton jrbNomeFornecedor;
    private javax.swing.JRadioButton jrbNomeFornecedor1;
    private javax.swing.JTable jtContasReceber;
    private javax.swing.JTable jtContasRecebidas;
    private javax.swing.JTextArea jtaObservacao;
    private javax.swing.JTextField jtfCobrar;
    private javax.swing.JTextField jtfCodigoCliente;
    private javax.swing.JTextField jtfCodigoConta;
    private javax.swing.JTextField jtfCodigoFormaPagamento1;
    private javax.swing.JTextField jtfCodigoPagamento;
    private com.toedter.calendar.JDateChooser jtfData;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfDescricaoConta;
    private javax.swing.JTextField jtfJuros;
    private javax.swing.JTextField jtfNumeroConta;
    private com.toedter.calendar.JDateChooser jtfPagamento;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JTextField jtfPesquisarRecebidas;
    private javax.swing.JTextField jtfReceber;
    private javax.swing.JTextField jtfTroco;
    private javax.swing.JTextField jtfValor;
    private javax.swing.JTextField jtfValorDivida;
    private com.toedter.calendar.JDateChooser jtfVencimento;
    private javax.swing.JTextField jtfVencimento1;
    private componentes.UJPanelImagem uJPanelImagem1;
    private componentes.UJPanelImagem uJPanelImagem2;
    private componentes.UJPanelImagem uJPanelImagem3;
    private componentes.UJPanelImagem uJPanelImagem4;
    private componentes.UJPanelImagem uJPanelImagem5;
    private componentes.UJPanelImagem uJPanelImagem6;
    private componentes.UJPanelImagem uJPanelImagem7;
    private componentes.UJPanelImagem uJPanelImagem8;
    // End of variables declaration//GEN-END:variables

    private void setIcone() {
        URL caminhoIcone = getClass().getResource("/imagens/icon.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
    }
}
